language: node_js
node_js:
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: npm
  email: hello@azinasili.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  tag: next
  on:
    tags: true
    branch: production
